// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJigCbMekPlYnTShF0KiTpoyFJy92LBU',
    appId: '1:177971910553:web:f4cebfadb8b82e3d7be508',
    messagingSenderId: '177971910553',
    projectId: 'elegant-90760',
    authDomain: 'elegant-90760.firebaseapp.com',
    storageBucket: 'elegant-90760.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChF6kghdOX0VWlJiFWFVzYJP71UPbVbmc',
    appId: '1:177971910553:android:2ca555104d34d72c7be508',
    messagingSenderId: '177971910553',
    projectId: 'elegant-90760',
    storageBucket: 'elegant-90760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85493c-_m3Ynk2b0dPw1afYWj00gXS74',
    appId: '1:177971910553:ios:133b3d91799d9f227be508',
    messagingSenderId: '177971910553',
    projectId: 'elegant-90760',
    storageBucket: 'elegant-90760.appspot.com',
    iosClientId: '177971910553-1ru5i8nve6le52qaevhl13gvdth5sgs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.elegant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85493c-_m3Ynk2b0dPw1afYWj00gXS74',
    appId: '1:177971910553:ios:133b3d91799d9f227be508',
    messagingSenderId: '177971910553',
    projectId: 'elegant-90760',
    storageBucket: 'elegant-90760.appspot.com',
    iosClientId: '177971910553-1ru5i8nve6le52qaevhl13gvdth5sgs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.elegant',
  );
}
